/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as CasaRouteImport } from './routes/casa'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ColecaoRouteImport } from './routes/colecao'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as OcasioesRouteImport } from './routes/ocasioes'
import { Route as ShopifyRouteImport } from './routes/shopify'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TrocasRouteImport } from './routes/trocas'
import { Route as ColecaoSlugRouteImport } from './routes/colecao.$slug'
import { Route as OcasioesSlugRouteImport } from './routes/ocasioes.$slug'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const CasaRoute = CasaRouteImport.update({
  id: '/casa',
  path: '/casa',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoRoute = ColecaoRouteImport.update({
  id: '/colecao',
  path: '/colecao',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const OcasioesRoute = OcasioesRouteImport.update({
  id: '/ocasioes',
  path: '/ocasioes',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopifyRoute = ShopifyRouteImport.update({
  id: '/shopify',
  path: '/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocasRoute = TrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoSlugRoute = ColecaoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ColecaoRoute,
} as any)
const OcasioesSlugRoute = OcasioesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OcasioesRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/atelier': typeof AtelierRoute
  '/boutique': typeof BoutiqueRoute
  '/casa': typeof CasaRoute
  '/checkout': typeof CheckoutRoute
  '/colecao': typeof ColecaoRouteWithChildren
  '/lookbook': typeof LookbookRoute
  '/ocasioes': typeof OcasioesRouteWithChildren
  '/shopify': typeof ShopifyRoute
  '/status': typeof StatusRoute
  '/trocas': typeof TrocasRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/ocasioes/$slug': typeof OcasioesSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/atelier': typeof AtelierRoute
  '/boutique': typeof BoutiqueRoute
  '/casa': typeof CasaRoute
  '/checkout': typeof CheckoutRoute
  '/colecao': typeof ColecaoRouteWithChildren
  '/lookbook': typeof LookbookRoute
  '/ocasioes': typeof OcasioesRouteWithChildren
  '/shopify': typeof ShopifyRoute
  '/status': typeof StatusRoute
  '/trocas': typeof TrocasRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/ocasioes/$slug': typeof OcasioesSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/atelier': typeof AtelierRoute
  '/boutique': typeof BoutiqueRoute
  '/casa': typeof CasaRoute
  '/checkout': typeof CheckoutRoute
  '/colecao': typeof ColecaoRouteWithChildren
  '/lookbook': typeof LookbookRoute
  '/ocasioes': typeof OcasioesRouteWithChildren
  '/shopify': typeof ShopifyRoute
  '/status': typeof StatusRoute
  '/trocas': typeof TrocasRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/ocasioes/$slug': typeof OcasioesSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/atelier'
    | '/boutique'
    | '/casa'
    | '/checkout'
    | '/colecao'
    | '/lookbook'
    | '/ocasioes'
    | '/shopify'
    | '/status'
    | '/trocas'
    | '/colecao/$slug'
    | '/ocasioes/$slug'
    | '/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/atelier'
    | '/boutique'
    | '/casa'
    | '/checkout'
    | '/colecao'
    | '/lookbook'
    | '/ocasioes'
    | '/shopify'
    | '/status'
    | '/trocas'
    | '/colecao/$slug'
    | '/ocasioes/$slug'
    | '/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/atelier'
    | '/boutique'
    | '/casa'
    | '/checkout'
    | '/colecao'
    | '/lookbook'
    | '/ocasioes'
    | '/shopify'
    | '/status'
    | '/trocas'
    | '/colecao/$slug'
    | '/ocasioes/$slug'
    | '/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AtelierRoute: typeof AtelierRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CasaRoute: typeof CasaRoute
  CheckoutRoute: typeof CheckoutRoute
  ColecaoRoute: typeof ColecaoRouteWithChildren
  LookbookRoute: typeof LookbookRoute
  OcasioesRoute: typeof OcasioesRouteWithChildren
  ShopifyRoute: typeof ShopifyRoute
  StatusRoute: typeof StatusRoute
  TrocasRoute: typeof TrocasRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casa': {
      id: '/casa'
      path: '/casa'
      fullPath: '/casa'
      preLoaderRoute: typeof CasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao': {
      id: '/colecao'
      path: '/colecao'
      fullPath: '/colecao'
      preLoaderRoute: typeof ColecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocasioes': {
      id: '/ocasioes'
      path: '/ocasioes'
      fullPath: '/ocasioes'
      preLoaderRoute: typeof OcasioesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopify': {
      id: '/shopify'
      path: '/shopify'
      fullPath: '/shopify'
      preLoaderRoute: typeof ShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocas': {
      id: '/trocas'
      path: '/trocas'
      fullPath: '/trocas'
      preLoaderRoute: typeof TrocasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao/$slug': {
      id: '/colecao/$slug'
      path: '/$slug'
      fullPath: '/colecao/$slug'
      preLoaderRoute: typeof ColecaoSlugRouteImport
      parentRoute: typeof ColecaoRoute
    }
    '/ocasioes/$slug': {
      id: '/ocasioes/$slug'
      path: '/$slug'
      fullPath: '/ocasioes/$slug'
      preLoaderRoute: typeof OcasioesSlugRouteImport
      parentRoute: typeof OcasioesRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ColecaoRouteChildren {
  ColecaoSlugRoute: typeof ColecaoSlugRoute
}

const ColecaoRouteChildren: ColecaoRouteChildren = {
  ColecaoSlugRoute: ColecaoSlugRoute,
}

const ColecaoRouteWithChildren =
  ColecaoRoute._addFileChildren(ColecaoRouteChildren)

interface OcasioesRouteChildren {
  OcasioesSlugRoute: typeof OcasioesSlugRoute
}

const OcasioesRouteChildren: OcasioesRouteChildren = {
  OcasioesSlugRoute: OcasioesSlugRoute,
}

const OcasioesRouteWithChildren = OcasioesRoute._addFileChildren(
  OcasioesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AtelierRoute: AtelierRoute,
  BoutiqueRoute: BoutiqueRoute,
  CasaRoute: CasaRoute,
  CheckoutRoute: CheckoutRoute,
  ColecaoRoute: ColecaoRouteWithChildren,
  LookbookRoute: LookbookRoute,
  OcasioesRoute: OcasioesRouteWithChildren,
  ShopifyRoute: ShopifyRoute,
  StatusRoute: StatusRoute,
  TrocasRoute: TrocasRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
